spring.application.name=mesatech-bff
server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=${ENTRA_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${ENTRA_AUDIENCE}

ms.solicitudes.url=${MS_SOLICITUDES_URL:http://localhost:8081}
ms.catalogo.url=${MS_CATALOGO_URL:http://localhost:8082}

logging.level.org.springframework.security=INFO
