spring.application.name=ms-solicitudes
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=${ENTRA_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${ENTRA_AUDIENCE}

spring.datasource.url=jdbc:postgresql://localhost:5432/mesatech_solicitudes
spring.datasource.username=${POSTGRES_USER:mesatech}
spring.datasource.password=${POSTGRES_PASSWORD:mesatech}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
